apiVersion: v1
kind: Pod
metadata:
  name: distroless-nginx
  labels:
    app: distroless-nginx
spec:
  shareProcessNamespace: true
  containers:
  - name: nginx
    image: kyos0109/nginx-distroless
    ports:
    - containerPort: 80
