#!/usr/bin/env bash
# ─── Generate Kubespray inventory from Terraform outputs ────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TF_DIR="$SCRIPT_DIR/../terraform"
INV_DIR="$SCRIPT_DIR/../inventory"

# Read JSON arrays into bash arrays
mapfile -t MPUB < <(terraform -chdir="$TF_DIR" output -json master_public_ips  | jq -r '.[]')
mapfile -t MINT < <(terraform -chdir="$TF_DIR" output -json master_internal_ips | jq -r '.[]')
mapfile -t WPUB < <(terraform -chdir="$TF_DIR" output -json worker_public_ips  | jq -r '.[]')
mapfile -t WINT < <(terraform -chdir="$TF_DIR" output -json worker_internal_ips | jq -r '.[]')

# Generate inventory.ini
cat > "$INV_DIR/inventory.ini" <<EOF
# Generated by 02-generate-inventory.sh
# Ansible connects via public IP (ansible_host), K8s binds to internal IP (ip)

master1 ansible_host=${MPUB[0]} ansible_user=ubuntu ip=${MINT[0]} etcd_member_name=etcd1
master2 ansible_host=${MPUB[1]} ansible_user=ubuntu ip=${MINT[1]} etcd_member_name=etcd2
master3 ansible_host=${MPUB[2]} ansible_user=ubuntu ip=${MINT[2]} etcd_member_name=etcd3
worker1 ansible_host=${WPUB[0]} ansible_user=ubuntu ip=${WINT[0]}
worker2 ansible_host=${WPUB[1]} ansible_user=ubuntu ip=${WINT[1]}

[kube_control_plane]
master1
master2
master3

[etcd:children]
kube_control_plane

[kube_node]
worker1
worker2
EOF

echo "Inventory written to $INV_DIR/inventory.ini"
cat "$INV_DIR/inventory.ini"
