apiVersion: v1
kind: Pod
metadata:
  name: s3-writer
spec:
  containers:
    - name: writer
      image: busybox:1.36
      command:
        - /bin/sh
        - -c
        - |
          while true; do
            echo "$(date) — alive" >> /data/healthcheck.txt
            sleep 30
          done
      volumeMounts:
        - name: s3-volume
          mountPath: /data
  volumes:
    - name: s3-volume
      persistentVolumeClaim:
        claimName: s3-pvc
  restartPolicy: Never
